all: drinks_bar atom_supplier molecule_requester

drinks_bar: drinks_bar.cpp
	g++ -o drinks_bar drinks_bar.cpp

atom_supplier: atom_supplier.cpp
	g++ -o atom_supplier atom_supplier.cpp

molecule_requester: molecule_requester.cpp
	g++ -o molecule_requester molecule_requester.cpp

clean:
	rm -f drinks_bar atom_supplier molecule_requester
	